server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #server-addr: localhost:8848 #配置Nacos地址
        server-addr: fsl.com:8888 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'
